### PR TITLE
Rename root artifact to match repository name

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/6)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/6#-:-KOit-GyQvf-mxuo2EuU:bnfp4nl)_

**Comment by denis-anisimov** [comment]
Parent POM should be updated to rename a module.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/6#-:-KOitNWHm-k7V3aE3-Ib:b9yo6ge)_

**Comment by Artur-** [comment]
fixed

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/6#-:-KOivb97EiZhy9R8DnBi:b-7ql1td)_

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/6)_

**Pull request merged**
