### PR TITLE
Mark complete and delete buttons for TodoMVC

### PR DESCRIPTION
**Pull request by pleku**
Uses ButtonRenderers with css content to create the proper images.
Styles the Grid to look more TodoMVC like.

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/28)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-KRhFjmlObjlWEaZAj-5:-KRhFjmlObjlWEaZAj-6:bf8pjdm) ([raw file](https://github.com/vaadin/framework8-demo/blob/c92cb57858e8974503d2787b96ca2b40a4336936/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java#L98)):_

> ```
>     grid.addColumn("", t -> "", new ButtonRenderer<>(
>             event -> presenter.markCompleted(event.getItem(),
>                     !event.getItem().isCompleted())));
> ```
> 
> I'd rather have a CheckBoxRenderer for this (in review at https://dev.vaadin.com/review/#/c/14412/), since styling a button to look like a checkbox seems a bit disingenuous.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Comment by pleku** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-KRhFjmlObjlWEaZAj-5:-KRhMUSAlFUgWmf-68jQ:b-o9sq3) ([raw file](https://github.com/vaadin/framework8-demo/blob/c92cb57858e8974503d2787b96ca2b40a4336936/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java#L98)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> > ```
> >     grid.addColumn("", t -> "", new ButtonRenderer<>(
> >             event -> presenter.markCompleted(event.getItem(),
> >                     !event.getItem().isCompleted())));
> > ```
> > 
> > I'd rather have a CheckBoxRenderer for this (in review at https://dev.vaadin.com/review/#/c/14412/), since styling a button to look like a checkbox seems a bit disingenuous.
> > </details>
> > I find it good enough since
> > a) it works like it should
> > b) checkboxrenderer is not in master
> > c) various other TodoMVC implementations also use a themed button instead of checkbox
> > d) a native checkbox is probably more difficult to override the theming to make it look like it should (which is not a target for us though)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-KRhFjmlObjlWEaZAj-5:-KRhO8Xte-DMAS0KeS_j:beblp7t) ([raw file](https://github.com/vaadin/framework8-demo/blob/c92cb57858e8974503d2787b96ca2b40a4336936/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java#L98)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> I find it good enough since
> a) it works like it should
> b) checkboxrenderer is not in master
> c) various other TodoMVC implementations also use a themed button instead of checkbox
> d) a native checkbox is probably more difficult to override the theming to make it look like it should (which is not a target for us though)
> </details>
> Valid arguments, but I would disagree with d: the "official" todomvcs use native checkboxes and share the same css. We should IMO strive towards keeping deviations from the official styling as small as possible. In any case this should probably be done in a separate patch.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Comment by ahie** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-:-KRhPOnztcjHBK2dUF1o:bnfp4nl)_

**Comment by hesara** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Comment by hesara** [comment]
can do what Aleksi suggested in a separate patch later

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-:-KRi-ygzzE4fzzh_Dikz:b-v8b0p5)_

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-KRhFjmlObjlWEaZAj-5:-KRlXMEl-esChEjJsLE6:bbythe1) ([raw file](https://github.com/vaadin/framework8-demo/blob/c92cb57858e8974503d2787b96ca2b40a4336936/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java#L98)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Valid arguments, but I would disagree with d: the "official" todomvcs use native checkboxes and share the same css. We should IMO strive towards keeping deviations from the official styling as small as possible. In any case this should probably be done in a separate patch.
> </details>
> then we need another ticket and need to change this

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Comment by ahie** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/28#-KRhFjmlObjlWEaZAj-5:-KRlbknm6RM2sha2jPQj:b-njbrfa) ([raw file](https://github.com/vaadin/framework8-demo/blob/c92cb57858e8974503d2787b96ca2b40a4336936/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoViewImpl.java#L98)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> then we need another ticket and need to change this
> </details>
> Added an issue for this

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/28)_

**Pull request merged**
