### PR TITLE
Basic TB tests for addressbook demo (#102).

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/5)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookTest.java, line 136 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOPVct75NOD5MnY00er:-KOPVct75NOD5MnY00es:b-2ep7h3) ([raw file](https://github.com/vaadin/framework8-demo/blob/f73585235c80bdc7e5d1af08c4336048c14af726/addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookTest.java#L136)):_

> ```
> private void hasText(WebElement element, String text) {
>     Assert.assertTrue(element.getAttribute("innerHTML").contains(text));
> }
> 
> private void hasNoText(WebElement element, String text) {
>     Assert.assertFalse(element.getAttribute("innerHTML").contains(text));
> }
> ```

Move to AbstractDemoTest?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Comment by denis-anisimov** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookTest.java, line 136 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOPVct75NOD5MnY00er:-KOPYyTOHeHYugXC1ck1:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/f73585235c80bdc7e5d1af08c4336048c14af726/addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookTest.java#L136)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> > ```
> > private void hasText(WebElement element, String text) {
> >     Assert.assertTrue(element.getAttribute("innerHTML").contains(text));
> > }
> > 
> > private void hasNoText(WebElement element, String text) {
> >     Assert.assertFalse(element.getAttribute("innerHTML").contains(text));
> > }
> > ```
> 
> Move to AbstractDemoTest?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Comment by Artur-** [comment]
Reviewed 2 of 23 files at r1, 10 of 19 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 21 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOyus2QH0uC6B-QPz:-KOiOyus2QH0uC6B-QQ-:b7c30oz) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L21)):_

> ``` Java
> @Title("Addressbook")
> @Theme(ValoTheme.THEME_NAME)
> public class AddressbookUI extends UI {
> ```

In what way is this related to TB tests?

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java, line 34 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPH9dD9DrlX9WkNYR:-KOiPH9eqSqGVW_Nrspf:b7c30oz) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java#L34)):_

> ``` Java
>     private static final ContactService INSTANCE = createDemoService();
> 
>     public static ContactService getDemoService() {
> ```

In what way is this related to TB tests?

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java, line 100 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPJ9NMIzMqb30Qqr7:-KOiPJ9NMIzMqb30Qqr8:b7c30oz) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java#L100)):_

> ``` Java
>         }
>         try {
>             entry = entry.clone();
> ```

In what way is this related to TB tests?

---

_[addressbook/src/main/resources/com/vaadin/tutorial/addressbook/ContactForm.html, line 7 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPNyQy67XXDIWtgX1:-KOiPNyR25FX-4DDldMN:bg2icqi) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/resources/com/vaadin/tutorial/addressbook/ContactForm.html#L7)):_

> ``` HTML
>  </head> 
>  <body> 
>   <vaadin-form-layout size-auto margin style-name="contactform"> 
> ```

any particular reason to use style-name instead of id?x

---

_[addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java, line 43 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPY5vbOw_Qo4yUyB9:-KOiPY5vbOw_Qo4yUyBA:b-c0f5yy) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java#L43)):_

> ``` Java
>     @Test
>     public void tableWithData() {
>         Assert.assertTrue(isElementPresent(By.className("contactstable")));
> ```

seems redundant as findElement throws an exception if the table is not found

---

_[addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java, line 120 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOid2ppFUeEPpWFe7AK:-KOid2ppFUeEPpWFe7AL:b-gzq8hx) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java#L120)):_

> ``` Java
>         Assert.assertFalse(isElementPresent(By.className("buttons")));
>     }
> ```

There should be a test where a contact is updated

---

_[test-util/pom.xml, line 32 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOi17F4AJfYfuFbtW:-KOiOi17F4AJfYfuFbtX:b-5rxr9x) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/test-util/pom.xml#L32)):_

> ``` XML
>     <build>
>         <plugins>
>             <plugin>
> ```

This is probably doable using a jetty.skip=true property

---

_[test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java, line 303 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOYCOGzehOljHiyyp:-KOiOYCPz12ruBRTtCxv:b-pia41l) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java#L303)):_

> ``` Java
>      *            a text to check against
>      */
>     protected void hasText(WebElement element, String text) {
> ```

make hasText return boolean to be consistent with hasCssClass and either do the assertion in the caller or create an assertHasText helper

---

_[test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java, line 304 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOicrQYcwCbCipG_DX8:-KOicrQYcwCbCipG_DX9:b-6z1f9t) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java#L304)):_

> ``` Java
>      */
>     protected void hasText(WebElement element, String text) {
>         Assert.assertTrue(element.getAttribute("innerHTML").contains(text));
> ```

why innerHTML and not WebElement.getText()?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 21 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOyus2QH0uC6B-QPz:-KOideLmQoDyJINSOK7d:b-2udfzx) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L21)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> In what way is this related to TB tests?
> </details>
> There is a mixture fixes for addressbook patch and this one.
> It has been fixed as a part of answers to a review. But apparently not in the previous PR.
> Is it a problem for this PR ?

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java, line 34 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPH9dD9DrlX9WkNYR:-KOieJxNo5R4XRrPw0wL:bgmjci0) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java#L34)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> In what way is this related to TB tests?
> </details>
> It's correction forgotten in previous PR.
> Has no direct relation.
> `synchronized` is not needed here.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java, line 100 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPJ9NMIzMqb30Qqr7:-KOieVZWubis2aaV_gLc:bdzherc) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/backend/ContactService.java#L100)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> In what way is this related to TB tests?
> </details>
> Correction that also should have been in previous patch. Without this `save` work incorrectly.

---

_[addressbook/src/main/resources/com/vaadin/tutorial/addressbook/ContactForm.html, line 7 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPNyQy67XXDIWtgX1:-KOiehiEJWkloWaJTAkR:b-3i8jx8) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/resources/com/vaadin/tutorial/addressbook/ContactForm.html#L7)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> any particular reason to use style-name instead of id?x
> </details>
> No, IT test is copy/paste from HB. So didn't think a lot ( or at all).

---

_[addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java, line 43 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiPY5vbOw_Qo4yUyB9:-KOievCRteBFx0s4tkrP:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java#L43)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> seems redundant as findElement throws an exception if the table is not found
> </details>
> Done.

---

_[test-util/pom.xml, line 32 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOi17F4AJfYfuFbtW:-KOif3ZYt2qOl0EX8t6a:b-hmzrwi) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/test-util/pom.xml#L32)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> This is probably doable using a jetty.skip=true property
> </details>
> skip is set by configuration here.
> It helps for avoiding start but stop is still waiting some time.
> But it looks you are right.

---

_[test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java, line 303 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOYCOGzehOljHiyyp:-KOih1wj13b3A_UI4Nef:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java#L303)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> make hasText return boolean to be consistent with hasCssClass and either do the assertion in the caller or create an assertHasText helper
> </details>
> Done.

---

_[test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java, line 304 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOicrQYcwCbCipG_DX8:-KOifKoSDAusU6VF7wgY:bi8f9uu) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/test-util/src/main/java/com/vaadin/demo/testutil/AbstractDemoTest.java#L304)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> why innerHTML and not WebElement.getText()?
> </details>
> Good question. getText() doesn't return expected value. I have no idea why. And don't want to spend time to dig Selenium here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Comment by Artur-** [comment]
Reviewed 1 of 19 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 21 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOiOyus2QH0uC6B-QPz:-KOimAfmURdQxQ1uJBQt:b-agya2r) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L21)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> There is a mixture fixes for addressbook patch and this one.
> It has been fixed as a part of answers to a review. But apparently not in the previous PR.
> Is it a problem for this PR ?
> </details>
> Not really

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Comment by denis-anisimov** [comment]
Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java, line 120 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/5#-KOid2ppFUeEPpWFe7AK:-KOinh-KetXFRIeZjli2:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/b453c31b9c8c17625432ce976b07883947346991/addressbook/src/test/java/com/vaadin/tutorial/addressbook/AddressbookIT.java#L120)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> There should be a test where a contact is updated
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Comment by Artur-** [comment]
Reviewed 1 of 19 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/5)_

**Pull request merged**
