### PR TITLE
Disable validation when adding a new contact

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/19)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KQt_ei4b_d7goGC27J7:bx3kfto) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_

> ``` Java
>         // Trigger cross-field validation when the other field is changed
>         email.addValueChangeListener(event -> {
>             if (event.isUserOriginated()) {
> ```

This approach just hides moves symptoms. The root cause seems to be that Binder doesn't reset its validation status when binding to a new item. You can still get things to break down e.g. in this way:

1) Click on a contact in the grid
2) Change the email address to something that doesn't pass the validator
3) Click on some other contact in the grid
4) The email field is still marked as invalid

Or another variation:

1) Click New contact
2) Click Save to trigger validation
3) Click New contact again
4) The old validation errors are still visible

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KQtepdNH5fA9P5D1j6H:b-ajdlub) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> This approach just hides moves symptoms. The root cause seems to be that Binder doesn't reset its validation status when binding to a new item. You can still get things to break down e.g. in this way:
> 
> 1) Click on a contact in the grid
> 2) Change the email address to something that doesn't pass the validator
> 3) Click on some other contact in the grid
> 4) The email field is still marked as invalid
> 
> Or another variation:
> 
> 1) Click New contact
> 2) Click Save to trigger validation
> 3) Click New contact again
> 4) The old validation errors are still visible
> </details>
> That's an issue that should be taken care of in the binder? Binder sets the component errors so it should also be responsible for clearing them on unbind, or provide a method for clearing validation errors?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KQthCtj57YhWXdbaH5H:b79i2wp) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> That's an issue that should be taken care of in the binder? Binder sets the component errors so it should also be responsible for clearing them on unbind, or provide a method for clearing validation errors?
> </details>
> That's at least how it appears to me. Fixing `Binder` to properly clear the component errors should be enough – no changes should be needed in the demo code.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KQtiIC2SkuKIUsry6fZ:b-vufblw) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> That's at least how it appears to me. Fixing `Binder` to properly clear the component errors should be enough – no changes should be needed in the demo code.
> </details>
> The bind() operation still changes the value of the original fields, causing a value change event, which in turn triggers the validators. This change accounts for that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KQtl-F-RttQIIqRaEen:b-ro3r2h) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> The bind() operation still changes the value of the original fields, causing a value change event, which in turn triggers the validators. This change accounts for that.
> </details>
> Improved the test to also test the aforementioned case. Build won't pass until binder has been changed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KQtmEC3kIrt6dDTmfyq:bbqlvuv) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Improved the test to also test the aforementioned case. Build won't pass until binder has been changed.
> </details>
> The bind operation should be aware that it has changed the fields and thus know that the validation component errors should be cleared. Therefore, these changes shouldn't be needed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRTS78UFDJEGP3hA_B-:b-svslx7) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> The bind operation should be aware that it has changed the fields and thus know that the validation component errors should be cleared. Therefore, these changes shouldn't be needed.
> </details>
> Yes, when https://dev.vaadin.com/review/#/c/14387 is merged the binder will clear the errors on rebind. Problem is once it clears the fields (new contact has empty email+phone in this case)  without this workaround these listeners initiate a new validation that would fail.

We should move the cross field validation to the binder level and error message to a status label instead of trying to get it to show up in component errors?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by pleku** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY1yUdRGJ8Q2xomaKf:b-ok9uvz) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Yes, when https://dev.vaadin.com/review/#/c/14387 is merged the binder will clear the errors on rebind. Problem is once it clears the fields (new contact has empty email+phone in this case)  without this workaround these listeners initiate a new validation that would fail.
> 
> We should move the cross field validation to the binder level and error message to a status label instead of trying to get it to show up in component errors?
> </details>
> Can you please test against the current master branch ?

Either this form is not working the way it should be (by calling `binder.validate()` on `valueChange`) or we need to fix something more.

Why does this even call binder.validate() since all field value changes trigger the validation (for that field and bean level if those pass) automatically ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by pleku** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY3AFIUsrE_Dz0BR5o:b-9uw5h) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Can you please test against the current master branch ?
> 
> Either this form is not working the way it should be (by calling `binder.validate()` on `valueChange`) or we need to fix something more.
> 
> Why does this even call binder.validate() since all field value changes trigger the validation (for that field and bean level if those pass) automatically ?
> </details>
> Oh right, cross field validation ...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY49Sp7rhh1hUrsr6u:b-r3p8j5) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Oh right, cross field validation ...
> </details>
> IMO this should just work as is, which means that the status clear should happen twice when doing load/bind, once in unbind since it can be called separately, and once after the new values have bean read in load/bind.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY4cLSCnyaGbYRA76-:b-82v33d) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> IMO this should just work as is, which means that the status clear should happen twice when doing load/bind, once in unbind since it can be called separately, and once after the new values have bean read in load/bind.
> </details>
> Yes it works as is now. But do we wan't to do "cross field validation" at the binding level. I believe Leif was also referring to the "isUserOriginated" workaround in his comments.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY5OE4cx3rCko5Ltsl:b-jv9flw) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Yes it works as is now. But do we wan't to do "cross field validation" at the binding level. I believe Leif was also referring to the "isUserOriginated" workaround in his comments.
> </details>
> Yes, I too meant the case of removing the check `event.isUserOriginated()`, it fails without it, right ?

As I said, probably need to do the "reset" validation status twice on on `Binder.load()` and `Binder.bind()`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY6wq_gDe7lxbBVvxb:b-yd009c) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Yes, I too meant the case of removing the check `event.isUserOriginated()`, it fails without it, right ?
> 
> As I said, probably need to do the "reset" validation status twice on on `Binder.load()` and `Binder.bind()`
> </details>
> Should probably be configurable, since sometimes you would want the validation errors to show up immediately?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY7G_udipQBYZTc1QN:b-2n89az) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Should probably be configurable, since sometimes you would want the validation errors to show up immediately?
> </details>
> I mean, is hiding them the best default behavior?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY7DS13urqgxtMOkub:bk7ya90) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> I mean, is hiding them the best default behavior?
> </details>
> Can be achieved by just calling `binder.validate()` after load/bind so don't think we need any configuration for that... and hiding was discussed as the way it should work when opening a new item.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRY9COzOuugQKNK4G2F:b-jmmnj8) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Can be achieved by just calling `binder.validate()` after load/bind so don't think we need any configuration for that... and hiding was discussed as the way it should work when opening a new item.
> </details>
> Sounds good to me. Will remove the isUserOriginated from this demo. An issue should be opened for ignoring the initial value change?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/19#-KQt_ei3Bqk_b6gjFfG2:-KRYApzDJ93VxvkKeGkV:btoeop4) ([raw file](https://github.com/vaadin/framework8-demo/blob/e3ec129746177dd0db2d408fc49fa2e1cf93e943/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L66)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Sounds good to me. Will remove the isUserOriginated from this demo. An issue should be opened for ignoring the initial value change?
> </details>
> No need for another issue IMO, I move the previous ticket back and will push another patch for it soon

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/19)_

**Pull request merged**
