### PR TITLE
Update TodoMvc to use new RadioButtonGroup

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/32)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[.gitignore, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-KSuiDi4pIaTTZpe-Axv:-KSuiDi5RSJYTYikkAJC:b-d0wxhj) ([raw file](https://github.com/vaadin/framework8-demo/blob/428250a4e64fc93abc2e83e033a9a1fd619fbf0f/.gitignore#L34)):_

> ```
> *.scss.cache
> 
> */error-screenshots/*
> ```

new line

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/Completion.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-KSuiVICg1dPNtRTqd-5:-KSuiVICg1dPNtRTqd-6:b-6nxnnn) ([raw file](https://github.com/vaadin/framework8-demo/blob/428250a4e64fc93abc2e83e033a9a1fd619fbf0f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/Completion.java#L23)):_

> ``` Java
>  * @author Vaadin Ltd
>  */
> public enum Completion {
> ```

Weird name: it's either completed or not.
May be just a TaskState ?
Or it's not a state actually.
TaskFilter? or whatever.......

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/Completion.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-KSuibwbfNXtVHUivlaQ:-KSuibwbfNXtVHUivlaR:b-1xbtum) ([raw file](https://github.com/vaadin/framework8-demo/blob/428250a4e64fc93abc2e83e033a9a1fd619fbf0f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/Completion.java#L25)):_

> ``` Java
> public enum Completion {
>     ALL {
>         @Override
> ```

Too verbose.
`getText()` can be implemented in a generic way e.g.: name().charAt(0)+name().substring(1).toLowerCase(Locale.ENGLISH);

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/32)_

**Comment by denis-anisimov** [comment]
Press the button ?

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-:-KT9kgcVv3weuGuFeKOD:b-ruxaym)_

**Comment by elmot** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[.gitignore, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-KSuiDi4pIaTTZpe-Axv:-KTDwF5S_p2BL4wQNAP4:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/428250a4e64fc93abc2e83e033a9a1fd619fbf0f/.gitignore#L34)):_
<details><summary>

<i>Previously, denis-anisimov (Denis) wrote…</i></summary>



> new line
> </details>
> Done.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TaskFilter.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-KSuiVICg1dPNtRTqd-5:-KTDwGtfBx1Dsbzic1Zd:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/428250a4e64fc93abc2e83e033a9a1fd619fbf0f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TaskFilter.java#L23)):_
<details><summary>

<i>Previously, denis-anisimov (Denis) wrote…</i></summary>



> Weird name: it's either completed or not.
> May be just a TaskState ?
> Or it's not a state actually.
> TaskFilter? or whatever.......
> </details>
> Done.

---

_[todomvc/src/main/java/com/vaadin/tutorial/todomvc/Completion.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/32#-KSuibwbfNXtVHUivlaQ:-KSuzKNKPHOnKIYM6UCe:bq4ferr) ([raw file](https://github.com/vaadin/framework8-demo/blob/428250a4e64fc93abc2e83e033a9a1fd619fbf0f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/Completion.java#L25)):_
<details><summary>

<i>Previously, denis-anisimov (Denis) wrote…</i></summary>



> Too verbose.
> `getText()` can be implemented in a generic way e.g.: name().charAt(0)+name().substring(1).toLowerCase(Locale.ENGLISH);
> </details>
> This is demo code, let it be as readable as possible.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/32)_

**Comment by denis-anisimov** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/32)_

**Pull request merged**
