### PR TITLE
Fix cancel in addressbook to correctly discard changes

### LINKED ISSUE #65: Addressbook cancel has no effect on new entry

### PR DESCRIPTION
**Pull request by ahie**
Closes #65

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/77)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLRwVjgKW_Ca2sIAEM:-KaLRwVjgKW_Ca2sIAEN:b-hbyf1f) ([raw file](https://github.com/vaadin/framework8-demo/blob/f2e28a4f50d256b170180601d1a112373f5f4079/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L100)):*
> ```Java
>         } else {
>             contactBeingEdited = null;
>             binder.removeBean();
> ```

This doesn't seem really logical here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLRwVjgKW_Ca2sIAEM:-KaLaqcyGgNHeGuFvxDl:bss4a2b) ([raw file](https://github.com/vaadin/framework8-demo/blob/f2e28a4f50d256b170180601d1a112373f5f4079/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L100)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This doesn't seem really logical here.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLRwVjgKW_Ca2sIAEM:-KaLjQ5e-lrk4B-X0Tcl:b-i34b8t) ([raw file](https://github.com/vaadin/framework8-demo/blob/f2e28a4f50d256b170180601d1a112373f5f4079/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L100)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Shouldn't `edit(null)` clear the values of all fields?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLRwVjgKW_Ca2sIAEM:-KaLofrpMmvtOaUoMjKU:bh9nrn0) ([raw file](https://github.com/vaadin/framework8-demo/blob/f2e28a4f50d256b170180601d1a112373f5f4079/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L100)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Shouldn't `edit(null)` clear the values of all fields?
</blockquote></details>

Didn't do this before, `binder.removeBean()` doesn't actually clear fields. Should binder actually have a method for clearing all bound fields, seeing as `HasValue` supports clearing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLqMukibgmkRPWnOYd:-KaLqMukibgmkRPWnOYe:b-2oxb4s) (no related file):*
What about a test?

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLRwVjgKW_Ca2sIAEM:-KaLpy9XSGH447fNWLxO:b-7jpe25) ([raw file](https://github.com/vaadin/framework8-demo/blob/f2e28a4f50d256b170180601d1a112373f5f4079/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L100)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Didn't do this before, `binder.removeBean()` doesn't actually clear fields. Should binder actually have a method for clearing all bound fields, seeing as `HasValue` supports clearing.
</blockquote></details>

It should probably, but that's not related to this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by ahie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KaLqMukibgmkRPWnOYd:-KaNCBgGXHFJ4i8EH--z:b-896fix) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What about a test?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by caalador** [comment]
As far as this ticket doesn't have to consider the fact that the bound fields will not be cleared.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 25 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KbFSGtQP6ZV48OLDp8x:-KbFSGtQP6ZV48OLDp8y:b-jc1k5x) ([raw file](https://github.com/vaadin/framework8-demo/blob/ce7b79db9cb4d7a027e1cdc372b96c1f191d2fd0/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L25)):*
> ```Java
>  * Create your own Vaadin components by inheritance and composition.
>  * This is a form component inherited from FormLayout. Use
>  * Use BeanFieldGroup to bind data fields from DTO to UI fields.
> ```

The BeanFieldGroup should be changed to binder.  Also `Use\nUse` could be single

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-:-KbFSbDHrA7WcWgdgPZq:b6ekbq0)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java, line 25 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-KbFSGtQP6ZV48OLDp8x:-Kbz8gN0skVFKNggnSaC:bb6un1j) ([raw file](https://github.com/vaadin/framework8-demo/blob/cfafc4782e66df8d72bd7cda7e31593dcbac4fd4/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactForm.java#L25)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The BeanFieldGroup should be changed to binder.  Also `Use\nUse` could be single
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Comment by caalador** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77#-:-Kc1x7cbPB1NRlIqBKsF:bnfp4nl)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/77)*

**Pull request merged**
