### PR TITLE
Fix registration-form issues #169, #170

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/14)

### CODE REVIEW

**Comment by Legioth** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 200 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/14#-KQVKpmPt2WUE6d6LI1T:-KQVKpmPt2WUE6d6LI1U:b8srqxt) ([raw file](https://github.com/vaadin/framework8-demo/blob/f67802d8c5ccbdef5f1a49efac60920c61fa648a/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L200)):_

> ``` Java
>                     Type.HUMANIZED_MESSAGE);
>         } else {
>             Notification.show(
> ```

All tests pass even if this change is commented out.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/14)_

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 200 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/14#-KQVKpmPt2WUE6d6LI1T:-KQVM2_3bjBxJyav5LoZ:b-5lz3uz) ([raw file](https://github.com/vaadin/framework8-demo/blob/f67802d8c5ccbdef5f1a49efac60920c61fa648a/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L200)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> All tests pass even if this change is commented out.
> </details>
> Will add a test.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/14)_

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 200 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/14#-KQVKpmPt2WUE6d6LI1T:-KQVP9Fbx8jQZKBcqQdn:bb6un1j) ([raw file](https://github.com/vaadin/framework8-demo/blob/f67802d8c5ccbdef5f1a49efac60920c61fa648a/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L200)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Will add a test.
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/14)_

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/14)_

**Pull request merged**
