### PR TITLE
Use CheckBoxGroup instead of a Custom field implementation (#155)

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change just replaces v7 CustomField with new CheckBoxGroup
component. As a result it breaks BeanFieldGroup usage since
CheckBoxGroup is not Field and cannot be used with FieldGroup.
In the end BeanFieldGroup should be replaced with (Bean)Binder and all
v7 Fields should be migrated to v8 HasValue components. But this is
separate issue: #157.

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/29)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/data/Category.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvfkYlb5-hkJqMdv5:-KRmvfkYlb5-hkJqMdv6:bdk7ku9) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/data/Category.java#L49)):_

> ``` Java
> 
>     @Override
>     public boolean equals(Object obj) {
> ```

Why is this needed?

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 79 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvVyh_K-ZQ4Ga4E6W:-KRmvVyh_K-ZQ4Ga4E6X:b-3ox1lc) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L79)):_

> ``` Java
> 
>     public void setCategories(Collection<Category> categories) {
>         category.setDataSource(DataSource.create(categories));
> ```

`category.setItems(categories)` is a bit simpler

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/29)_

**Comment by pleku** [comment]
Reviewed 5 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvk8bdBt4_qd22tWI:-KRmvk8bdBt4_qd22tWJ:b-mm2gfp) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L173)):_

> ``` Java
>     }
> 
>     private void init(SampleCrudLogic logic) {
> ```

not related to this ticket, but this should be a setter not another init method with overridden parameter

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvUt-haUFPlUeYbke:-KRmvUt-haUFPlUeYbkf:bgg4apt) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L178)):_

> ``` Java
> 
>     @PostConstruct
>     private void initComponents() {
> ```

why oh why another `@PostConstruct`init methods? this one even nicely hidden at the end of this file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/29)_

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/data/Category.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvfkYlb5-hkJqMdv5:-KRmyTREFw5eKdV4WDdl:byxwog1) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/data/Category.java#L49)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Why is this needed?
> </details>
> 
> ``` java
> private void selectCategories(Product product) {
>         category.getSelectionModel().deselectAll();
>         if (product.getCategory() != null) {
>             product.getCategory().stream()
>                     .forEach(category.getSelectionModel()::select);
>         }
>     }
> ```

doesn't work without this. Of course it's possible to write different code but it will be more complicated.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 79 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvVyh_K-ZQ4Ga4E6W:-KRmyo5YY5YZb7-_T28U:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L79)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> `category.setItems(categories)` is a bit simpler
> </details>
> Done.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvk8bdBt4_qd22tWI:-KRmyu7rpgZ4IXPBgTQ6:b-8svq6b) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L173)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> not related to this ticket, but this should be a setter not another init method with overridden parameter
> </details>
> This must not be setter and this is done intentionally from the very beginning.

Setter allows to set value at any time by anyone.
But here it has to be done only once at the initialization phase only.
Normally it should be in the CTOR.
But that's the limitation of using Spring: you can't use constructors with parameters that cannot be injected.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/29#-KRmvUt-haUFPlUeYbke:-KRmzRHyzsA1VqYNHqSL:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/7a7d0d53fdb187469c61012bf33858c0043fb996/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L178)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> why oh why another `@PostConstruct`init methods? this one even nicely hidden at the end of this file
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/29)_

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/29)_

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/29)_

**Pull request merged**
