### PR TITLE
Demo for using a REST API directly from Grid through JsonObjects

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/22)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRYbYPjGqGlqPlvSu8r:-KRYbYPkglOl0lrqIg0F:be8052u) ([raw file](https://github.com/vaadin/framework8-demo/blob/843947d0341621860cf1c497c07c1a7e7b7a896e/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L59)):_

> ``` Java
>                 return jsonArrayStream(results);
>             } catch (IOException e) {
>                 e.printStackTrace();
> ```

(could handle errors more gracefully - haven't checked if the other demos do the same)

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRYcfdbkfTsV6fC3Qlr:-KRYcfdbkfTsV6fC3Qls:b-bcrqoq) ([raw file](https://github.com/vaadin/framework8-demo/blob/843947d0341621860cf1c497c07c1a7e7b7a896e/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L69)):_

> ``` Java
>     }
> 
>     private static Stream<JsonObject> jsonArrayStream(JsonArray array) {
> ```

would be even cleaner without the wrapping into a List, e.g. something like IntStream.range(0, array.length()).map(i -> array.getObject(i))

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRYbYPjGqGlqPlvSu8r:-KRZxGRerGnpjZ-UqQsy:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/843947d0341621860cf1c497c07c1a7e7b7a896e/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L59)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (could handle errors more gracefully - haven't checked if the other demos do the same)
> </details>
> Done.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRYcfdbkfTsV6fC3Qlr:-KRZwcMCJUGj3IVYuvT9:brhmzj1) ([raw file](https://github.com/vaadin/framework8-demo/blob/843947d0341621860cf1c497c07c1a7e7b7a896e/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L69)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> would be even cleaner without the wrapping into a List, e.g. something like IntStream.range(0, array.length()).map(i -> array.getObject(i))
> </details>
> Now using JsonUtil from the framework project

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by hesara** [comment]
:lgtm: but probably should wait until the corresponding framework change before merging this

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-:-KRb7NXu-yUa-B2CIfO9:b-9ade1l)_

**Comment by denis-anisimov** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

_[rest-json-datasource-demo/README.md, line 14 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbFL-0H_qM4HatsGyR:-KRbFL-1ZKhKnoAlvnPo:b-d0wxhj) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/README.md#L14)):_

> ``` Markdown
> ```
> 
> after which the application is accessible at http://localhost:8888/
> 
> ```
> ```

new line

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 52 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbFV_UEFa5ctr0DuOH:-KRbFV_UEFa5ctr0DuOI:bixutm5) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L52)):_

> ``` Java
> 
>         personGrid.setDataSource(new BackEndDataSource<JsonObject>(query -> {
>             URL url;
> ```

Please extract this lambda to a method. It's too long.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbG2M-c9pqwX-hxy0l:-KRbG2M-c9pqwX-hxy0m:b-a6sbpm) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L75)):_

> ``` Java
> 
>     private String safeGetString(JsonObject json, String... path) {
>         for (int i = 0; i < path.length - 1; i++) {
> ```

I'm not sure I understand the purpose of navigation through the `path` array without doing anything with its values.
But use `Stream.of(path).map(...).anyMatch()`

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 81 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbGVPQkfC30JVEGw9m:-KRbGVPQkfC30JVEGw9n:bnofofu) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L81)):_

> ``` Java
>             }
>         }
>         JsonValue value = json.get(path[path.length - 1]);
> ```

And here only last path segment is used.
So the array `path` is actually not needed ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 81 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbfcSMNLLRGJTxqj_5:-KRbfcSMNLLRGJTxqj_6:b-wji5oj) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L81)):_
<details><summary>

<i alt="summary">Quoted 4 lines of code…</i></summary>



> ```
>     JsonValue value = json.get(path[path.length - 1]);
>     if (value == null) {
>         return "";
>     }
> ```
> 
> </details>
> Why is this not in the preceding for loop?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

_[rest-json-datasource-demo/README.md, line 14 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbFL-0H_qM4HatsGyR:-KRbeT1SJWhrxEVXRsUL:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/README.md#L14)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> new line
> </details>
> Done.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 52 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbFV_UEFa5ctr0DuOH:-KRbfGQ_oQCGDd5yXaqM:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L52)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> Please extract this lambda to a method. It's too long.
> </details>
> Done.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbG2M-c9pqwX-hxy0l:-KRbfIakxNF-Y4MvL4c9:bqepbb1) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L75)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> I'm not sure I understand the purpose of navigation through the `path` array without doing anything with its values.
> But use `Stream.of(path).map(...).anyMatch()`
> </details>
> The point is to terminate the lookup if a missing value (null) is encountered. Probably could be done with a stream also

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by Artur-** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 81 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbfcSMNLLRGJTxqj_5:-KRbgGtwFsmSStvBfkn5:b-r2xpu2) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L81)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> > ```
> >     JsonValue value = json.get(path[path.length - 1]);
> >     if (value == null) {
> >         return "";
> >     }
> > ```
> > 
> > Why is this not in the preceding for loop?
> > </details>
> > The return value cannot be cast to JsonObject

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by denis-anisimov** [comment]
Reviewed 2 of 3 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by denis-anisimov** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

_[rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java, line 81 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/22#-KRbGVPQkfC30JVEGw9m:-KRbgqWkZefE84W3IPRc:b-oe37u3) ([raw file](https://github.com/vaadin/framework8-demo/blob/ab074deb6bbc0c0f7dfe31b0c4a28b72907bbbd0/rest-json-datasource-demo/src/main/java/com/vaadin/framework8/demo/restjson/RESTDemoUI.java#L81)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> And here only last path segment is used.
> So the array `path` is actually not needed ?
> </details>
> the for loop updates what "json" refers to

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/22)_

**Pull request merged**
