### PR TITLE
Inline editing in Grid for TodoMVC

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/24)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/24#-KRc5rrZXWw62hGD9nQn:-KRc5rrZXWw62hGD9nQo:bsnn85r) ([raw file](https://github.com/vaadin/framework8-demo/blob/80d72b00f954be95e04be231fff2cb71ca5bc31b/todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java#L205)):_

> ``` Java
> 
>     private void verifyInlineEditorNotPresent() {
>         try {
> ```

I would prefer the line 

``` Assert.assertTrue(isElementPresent(By.id("todo-editor")));```
instead of this try-catch. Even if it allows to avoid duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/24)*

```

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/24#-KRc5rrZXWw62hGD9nQn:-KRcVvSqRp_Inbf34Nd0:b-gsscft) ([raw file](https://github.com/vaadin/framework8-demo/blob/80d72b00f954be95e04be231fff2cb71ca5bc31b/todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java#L205)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> I would prefer the line 
> 
> `````` Assert.assertTrue(isElementPresent(By.id("todo-editor")));```
> instead of this try-catch. Even if it allows to avoid duplication.
> 
> </details>
> WAT? Please use ```code blocks correctly```
> ``````

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/24)_

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/24#-KRc5rrZXWw62hGD9nQn:-KRcWnH8S9dWho-2VN0j:b-95k2nm) ([raw file](https://github.com/vaadin/framework8-demo/blob/4be86d8d350ffc8139e54cc5971919f76dd4cd7b/todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java#L205)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> WAT? Please use `code blocks correctly`
> </details>
> Argh....

``` java
Assert.assertTrue(isElementPresent(By.id("todo-editor")));
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/24)_

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/24#-KRc5rrZXWw62hGD9nQn:-KRc_1S1-WvKQUAiFImG:b-xalhwb) ([raw file](https://github.com/vaadin/framework8-demo/blob/4be86d8d350ffc8139e54cc5971919f76dd4cd7b/todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java#L205)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> Argh....
> 
> ``` java
> Assert.assertTrue(isElementPresent(By.id("todo-editor")));
> ```
> 
> </details>
> Forgot that one, it is much better, is it OK if I fix in next patch (with complete and delete buttons) ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/24)_

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/24#-KRc5rrZXWw62hGD9nQn:-KRcb-KH4CbxGuYqt4gw:b32w0x) ([raw file](https://github.com/vaadin/framework8-demo/blob/4be86d8d350ffc8139e54cc5971919f76dd4cd7b/todomvc/src/test/java/com/vaadin/tutorial/todomvc/TodoMvcIT.java#L205)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Forgot that one, it is much better, is it OK if I fix in next patch (with complete and delete buttons) ?
> </details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/24)_

**Pull request merged**
