### PR TITLE
Add tree-database-example

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/86)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 8 of 14 files at r1.
Review status: 8 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2PtSWKciiO712_82a:-Kl2PtSWKciiO712_82b:b-e7ksvm) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java#L27)):*
> getDataSource()

Couldn't this be replaced with DriverManager.getConnection() and initialized with a separate call? This seems to only be called to get the connection.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2VJBkbmXYvrj43xF1:-Kl2VJBkbmXYvrj43xF2:bz3v561) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L19)):*
> PeopleData

`PeopleDataProvider`?

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2VN7q8HSXw3wpJOrz:-Kl2VN7q8HSXw3wpJOs-:bix3701) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L19)):*
> AbstractHierarchicalDataProvider

`AbstractBackEndHierarchicalDataProvider`.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2R_ITd6_cx8wfXO64:-Kl2R_ITd6_cx8wfXO65:bifdxrr) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L28)):*
> "select count(*) from people where department_id=?"

Could be moved to be constants.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2RgkgGVXRIUBtuwlp:-Kl2RgkgGVXRIUBtuwlq:b-bo1kh5) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L46)):*
> "SELECT * FROM people WHERE department_id=?"

nit: inconsistent use of capitalization

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2TOuXGv8keslB3dsd:-Kl2TOuXGv8keslB3dse:bgtfz1s) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L74)):*
> for(int i = 0; i < query.getOffset();i++)
> {
>     if(!resultSet.next()) return Stream.empty();
> }

`resultSet.absolute(query.getOffset())` or `resultSet.relative(query.getOffset())`?

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2TEGJnPf2SxZGE9OK:-Kl2TEGKoXKMfeZhz1t1:b-es49po) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L113)):*
> resultSet.next()

`if (resultSet.next())` ?

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2SmJMARnCSg9oh_0K:-Kl2SmJNOo5mzCdZ8VeV:blpegv5) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java#L110)):*
> public static class EmailGenerator

Shouldn't emails be in the database? This distracts from the main point of the demo.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/pojo/NamedItem.java, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2RrHoAcZPMXwYKTn2:-Kl2RrHoAcZPMXwYKTn3:biihgu6) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/pojo/NamedItem.java#L7)):*
> long id;

IDs seem to be INT in the database table creation.

---

*[tree-database-example/src/main/resources/org/vaadin/example/treegrid/jdbc/db_ddl.sql, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2S1OnDI5wALRs8hhz:-Kl2S1OnDI5wALRs8hi-:bjyytk6) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/resources/org/vaadin/example/treegrid/jdbc/db_ddl.sql#L11)):*
> create table

nit: newline, capitalize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/86)*

**Comment by elmot** [comment]
Review status: 5 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2PtSWKciiO712_82a:-KlILLKDL1W8-fm5Rt7U:b-u4j24i) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java#L27)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> getDataSource()

Couldn't this be replaced with DriverManager.getConnection() and initialized with a separate call? This seems to only be called to get the connection.
</blockquote></details>

This method is an example code to demonstrate:
 - using of Apache DBCP
 - thread-safe SQL connection handling
 - providing this code as a code example for a blog post, FAQs etc. 

That are the reasons for using the code, which at first glance looks like overhead.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleDataProvider.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2TOuXGv8keslB3dsd:-KlIWFj79jb3Dj7vUQv7:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleDataProvider.java#L74)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> for(int i = 0; i < query.getOffset();i++)
> {
>     if(!resultSet.next()) return Stream.empty();
> }

`resultSet.absolute(query.getOffset())` or `resultSet.relative(query.getOffset())`?

</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2SmJMARnCSg9oh_0K:-KlIKbMxYy2E_q_wKkC6:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java#L110)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> public static class EmailGenerator

Shouldn't emails be in the database? This distracts from the main point of the demo.
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/pojo/NamedItem.java, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2RrHoAcZPMXwYKTn2:-KlIHwzz6XER2yGRdOLO:bna8as) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/pojo/NamedItem.java#L7)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> long id;

IDs seem to be INT in the database table creation.
</blockquote></details>

Now BIGINT in the 
Done

---

*[tree-database-example/src/main/resources/org/vaadin/example/treegrid/jdbc/db_ddl.sql, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2S1OnDI5wALRs8hhz:-KlII2AaYEX27Y3HQ90e:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/resources/org/vaadin/example/treegrid/jdbc/db_ddl.sql#L11)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> create table

nit: newline, capitalize
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2VN7q8HSXw3wpJOrz:-KlILIZFjBBtItPlXkhb:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L19)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> AbstractHierarchicalDataProvider

`AbstractBackEndHierarchicalDataProvider`.
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2VJBkbmXYvrj43xF1:-KlILJJIN0kbAEOVKByx:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L19)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> PeopleData

`PeopleDataProvider`?
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2R_ITd6_cx8wfXO64:-KlIKfmA8cgJuBwA1E7Y:b-ae3s9) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L28)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> "select count(*) from people where department_id=?"

Could be moved to be constants.
</blockquote></details>

I don't see any value out from that in this particular example.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2RgkgGVXRIUBtuwlp:-KlIKeFLZJlOYwwtNvpl:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L46)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> "SELECT * FROM people WHERE department_id=?"

nit: inconsistent use of capitalization
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kl2TEGJnPf2SxZGE9OK:-KlIMMJhxqnYRR06ptYi:b74ibmy) ([raw file](https://github.com/vaadin/framework8-demo/blob/5824111139e4afa173ec9df84e2e3d04f59618de/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleData.java#L113)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> resultSet.next()

`if (resultSet.next())` ?
</blockquote></details>

The method is supposed to be used with SQLs of type `select count(*) from foo`. Those methods always return a single-value result set until SQL is incorrect or DB connection is broken. I don't see a reason to add more complications with extra errors handling for those cases, let's assume SQL server diagnostics is enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/86)*

**Comment by torok-peter** [comment]
Reviewed 8 of 15 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pom.xml, line 44 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs0RsnpDB7pxlMEhRT:-Kxs0RsorhxPry873O4E:b-aucl11) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/pom.xml#L44)):*
> ```XML
>         <module>spring-demo</module>
>         <module>todomvc</module>
> 	<module>tree-database-example</module>
> ```

Replace tab with spaces

---

*[tree-database-example/pom.xml, line 9 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs0_PE2uAWr0L315X-:-Kxs0_PE2uAWr0L315X0:bgila68) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/pom.xml#L9)):*
> ```XML
>         <groupId>com.vaadin.framework8</groupId>
>         <artifactId>framework8-demo</artifactId>
>         <version>8.0-SNAPSHOT</version>
> ```

I guess this should be updated by now?

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs3AJPSi3Paeo35jZO:-Kxs3AJPSi3Paeo35jZP:bgwx82v) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java#L22)):*
> ```Java
> @SuppressWarnings("WeakerAccess")
> public class DBEngine {
>     private static BasicDataSource dataSource;
> ```

This should be `volatile` or else double-checked locking is not thread-safe; or preferably, use the Initialization-on-demand holder idiom instead:
https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleDataProvider.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs5TX_8kRWFk0b8w1E:-Kxs5TX_8kRWFk0b8w1F:b-f98dh6) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleDataProvider.java#L67)):*
> ```Java
>                     resultSet.getString("company_email"));
>         }
>         try (Connection connection = DBEngine.getDataSource().getConnection();
> ```

The rest of the method could be extracted to improve readability

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java, line 47 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs68vG0Q-d_2T9Wtff:-Kxs68vG0Q-d_2T9Wtfg:b-9yt04x) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java#L47)):*
> ```Java
> 
>         tree.addExpandListener(expandEvent -> treeGrid.expand(expandEvent.getExpandedItem()));
>         tree.addCollapseListener(expandEvent -> treeGrid.collapse(expandEvent.getCollapsedItem()));
> ```

This setup of mutually listening to each other's expand and collapse event looks a bit strange at first sight; an explanatory comment could be useful 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/86)*

**Comment by elmot** [comment]
Review status: 9 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[pom.xml, line 44 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs0RsnpDB7pxlMEhRT:-KxvtNKMQGNGPBWmgRui:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/pom.xml#L44)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Replace tab with spaces
</blockquote></details>

Done.

---

*[tree-database-example/pom.xml, line 9 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs0_PE2uAWr0L315X-:-KxvtT3Qr63xjqTK_S0d:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/pom.xml#L9)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

I guess this should be updated by now?
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs3AJPSi3Paeo35jZO:-KxvvmOyxkQuCiw1mvPA:b-vgllz4) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/DBEngine.java#L22)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

This should be `volatile` or else double-checked locking is not thread-safe; or preferably, use the Initialization-on-demand holder idiom instead:
https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom
</blockquote></details>

Cool stuff, thanks! Done

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleDataProvider.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs5TX_8kRWFk0b8w1E:-KxvyGgTXxKzOpElf7oe:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/PeopleDataProvider.java#L67)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

The rest of the method could be extracted to improve readability
</blockquote></details>

Done.

---

*[tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java, line 47 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/86#-Kxs68vG0Q-d_2T9Wtff:-Kxvz5MwGcF5v_wbrQbJ:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/742593369dde26eb719fbb7acf9a75aa8a0965ce/tree-database-example/src/main/java/org/vaadin/example/treegrid/jdbc/TreeUI.java#L47)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

This setup of mutually listening to each other's expand and collapse event looks a bit strange at first sight; an explanatory comment could be useful 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/86)*

**Comment by torok-peter** [comment]
Reviewed 1 of 7 files at r2, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/86)*

**Pull request merged**
