### PR TITLE
Reimplement filtering in Spring demo

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch changes a bit on how the Transactionality of the Repositories is done. CRUD methods are transactional by default and our fetch method has now been explicitly marked to be transactional.

Adds push support to demonstrate the shared data provider approach.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/52)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/CategoryRepository.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-KXBcYct9G3kpuvd3LSf:-KXBcYct9G3kpuvd3LSg:bi0p14l) ([raw file](https://github.com/vaadin/framework8-demo/blob/ec7340b4f519c4ae7a03a6e9a3fa7124a04ea770/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/CategoryRepository.java#L36)):*
> ```Java
>  *
>  */
> @Transactional(TxType.MANDATORY)
> ```

when removing this, please check that all users of the repository use transactions correctly

---

*[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/ProductRepository.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-KXBd57OQvnlfYnDy08E:-KXBd57OQvnlfYnDy08F:bi0p14l) ([raw file](https://github.com/vaadin/framework8-demo/blob/ec7340b4f519c4ae7a03a6e9a3fa7124a04ea770/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/ProductRepository.java#L40)):*
> ```Java
>  *
>  */
> @Transactional(TxType.MANDATORY)
> ```

when removing this, please check that all users of the repository use transactions correctly

---

*[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataProviderImpl.java, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-KXBeHs0cLn6le-AtCLF:-KXBeHs0cLn6le-AtCLG:b-kmukx4) ([raw file](https://github.com/vaadin/framework8-demo/blob/d3007e8e5deff794799c104fda355548135a72ed/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataProviderImpl.java#L60)):*
> ```Java
>     @Transactional
>     public int size(Query<Supplier<String>> t) {
>         return (int) getItems(getPaging(t).pageable,
> ```

could extract the common part to a private method

---

*[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-KXBdDYSRoIkMxu2Al6y:-KXBdDYSRoIkMxu2Al6z:bb3l9si) ([raw file](https://github.com/vaadin/framework8-demo/blob/d3007e8e5deff794799c104fda355548135a72ed/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L58)):*
> ```Java
>         filter.setStyleName("filter-textfield");
>         filter.setPlaceholder("Filter");
>         filter.addValueChangeListener(event -> dataProvider.refreshAll());
> ```

this approach could perhaps use a comment here and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/52)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/52)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 159 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-KXigumbrl8jXw37Zgdn:-KXigumdLFsgpCRIBOWx:bjadwiw) ([raw file](https://github.com/vaadin/framework8-demo/blob/61158d6c66ccf2dde02ac90a9a4e0ec1c8b7f244/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L159)):*
> ```Java
>             binder.readBean(currentProduct);
>         } else {
>             binder.removeBean();
> ```

TBC: does creating a new product work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/52)*

**Comment by tsuoanttila** [comment]
Travis build passed with the snapshot from last night.

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java, line 159 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-KXigumbrl8jXw37Zgdn:-KXjJv4SN9Gk5SdnlMK4:bm0tmt) ([raw file](https://github.com/vaadin/framework8-demo/blob/61158d6c66ccf2dde02ac90a9a4e0ec1c8b7f244/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductForm.java#L159)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC: does creating a new product work?
</blockquote></details>

tested, seems to work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/52#-:-KXjJzRKcTFf66YD_wDx:bnfp4nl)*

**Pull request merged**
