### PR TITLE
Fix compilation error in demos against current V8 master branch (#246).

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/21)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/21#-KRYKG8M554o6ec-Tm_H:-KRYKG8NxmSRgmtoNEy8:b-qkmdmk) ([raw file](https://github.com/vaadin/framework8-demo/blob/6957e3cf3e8c52cc68f0968eeed9726f77ea121c/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L126)):_

> ``` Java
> 
>     private void commonStatusChangeHandler(ValidationStatus<?> event,
>             HasValue<?> field) {
> ```

Make field `AbstractField` to avoid the cast below

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/21)_

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/21#-KRYKG8M554o6ec-Tm_H:-KRYLDAZNbIQ_nOltcyP:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/6957e3cf3e8c52cc68f0968eeed9726f77ea121c/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L126)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Make field `AbstractField` to avoid the cast below
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/21)_

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/21)_

**Comment by ahie** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/21)_

**Pull request merged**
