### PR TITLE
Fix data provider imports

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/71)

### CODE REVIEW

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/71#-:-KZ1MncZv24PwmzL1qif:bnfp4nl)*

**Comment by tsuoanttila** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/71#-:-KZ1f0xxDOXo2-Hu8RuV:bnfp4nl)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/71#-:-KZ1fTY1aSSNsMbSUCHu:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/71)*

**Pull request merged**
