### PR TITLE
Use new Grid for Spring demo

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/23)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRbqqPwdNfhfZYpCnTu:-KRbqqPwdNfhfZYpCnTv:b-8y7sdp) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java#L76)):_

> ``` Java
>                             t.getCategory())
>                     .map(String::valueOf)
>                     .filter(s -> s.toLowerCase().contains(text.toLowerCase()))
> ```

ideally should use locale for toLowerCase(); instead of filter() followed by count() check, use anyMatch(Predicate)

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 123 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRboLxZiVasQPCaNeX0:-KRboLxZiVasQPCaNeX1:b-8fcta9) ([raw file](https://github.com/vaadin/framework8-demo/blob/a2c337ab52f22b451ae3b1e64d5087b883e18bf7/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L123)):_

> ``` Java
>     public void refreshProduct(Product product) {
>         grid.refresh(product);
>         grid.scrollTo(product);
> ```

any replacement for this? or a comment?

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRboR6bq1yNPZGu7oJR:-KRboR6bq1yNPZGu7oJS:bf09s60) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L126)):_

> ``` Java
> 
>     public void removeProduct(Product product) {
>         // TODO: Remove from the back end, inform grid of change.
> ```

when can this be addressed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRboR6bq1yNPZGu7oJR:-KRbtK6FZjX3kT3O9nzb:b5t0wrg) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L126)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> when can this be addressed?
> </details>
> Easiest way for now would be to get .refreshAll() in DataSource and migrate to using the real backend directly. Then it should "Just Work" although inefficiently

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 123 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRboLxZiVasQPCaNeX0:-KRbtF_Y-iQewbkxHKIa:bgmaq2o) ([raw file](https://github.com/vaadin/framework8-demo/blob/a2c337ab52f22b451ae3b1e64d5087b883e18bf7/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L123)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> any replacement for this? or a comment?
> </details>
> Scroll to has not been implemented yet, could add a comment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRbqqPwdNfhfZYpCnTu:-KRbtYQFrzRLwoDs8JIo:bhpwc22) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java#L76)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> ideally should use locale for toLowerCase(); instead of filter() followed by count() check, use anyMatch(Predicate)
> </details>
> Will take a look at this soon. The filter was written really quickly..

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRc8m6IOpSWRDu2o9Nc:-KRc8m6IOpSWRDu2o9Nd:bglzsey) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java#L60)):_

> ``` Java
>     }
> 
>     public Product getSelectedRow() {
> ```

Should it be Optional<Product> ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRc8m6IOpSWRDu2o9Nc:-KRcBSS8oJWFbz8cgaBA:bntysq1) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductGrid.java#L60)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> Should it be Optional<Product> ?
> </details>
> I wanted to keep the changes minimal. Yes, we should change it to returning optional at some point.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRboR6bq1yNPZGu7oJR:-KRcDRR7r9aL7QB_3Xv_:b-46t7bq) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L126)):_
<details><summary>

<i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary>



> Easiest way for now would be to get .refreshAll() in DataSource and migrate to using the real backend directly. Then it should "Just Work" although inefficiently
> </details>
> can be addressed later - could add a ticket to finalize the demo

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-:-KRcDcR9YPtTtkKhDsj_:bnfp4nl)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 126 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/23#-KRboR6bq1yNPZGu7oJR:-KRcDgr48iLDWQ4CFcSd:b-w5b18r) ([raw file](https://github.com/vaadin/framework8-demo/blob/ada39dc6ff26a0415fe30754c398f81e76930746/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L126)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> can be addressed later - could add a ticket to finalize the demo
> </details>
> Added a comment to the ticket about using the actual repository.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/23)_

**Pull request merged**
