### PR TITLE
Add a ProductDataSource to use with Grid

### PR DESCRIPTION
**Pull request by tsuoanttila**
Simplifier ProductDataSource without actual lazy loading. Has support for filtering with the back end instead of an in memory filter.

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/27)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/CategoryRepository.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRgxoUzYJ6oqzti4Nf7:-KRgxoV-ouZ2UaNmIgel:beidfmz) ([raw file](https://github.com/vaadin/framework8-demo/blob/4c15f1a6f27da15dde14deb3dadd30837cf3ef8f/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/CategoryRepository.java#L36)):_

> ``` Java
>  *
>  */
> // @Transactional(TxType.MANDATORY)
> ```

why no longer transactional?

---

_[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/ProductRepository.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRgxxH29DaSmnVTbnuV:-KRgxxH29DaSmnVTbnuW:bsm2e2b) ([raw file](https://github.com/vaadin/framework8-demo/blob/4c15f1a6f27da15dde14deb3dadd30837cf3ef8f/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/ProductRepository.java#L36)):_

> ``` Java
>  *
>  */
> // @Transactional(TxType.MANDATORY)
> ```

why removed transactional?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/CategoryRepository.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRgxoUzYJ6oqzti4Nf7:-KRh6_zWuD0ENyHgJcRu:b2xv7tj) ([raw file](https://github.com/vaadin/framework8-demo/blob/4c15f1a6f27da15dde14deb3dadd30837cf3ef8f/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/CategoryRepository.java#L36)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> why no longer transactional?
> </details>
> I had some problem with the transactionality with the alternative find methods. I think it's just something I'm missing from there, could be restored if someone helps me understand why it didn't work.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r1, 4 of 5 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 66 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhP5iUcMjdExYRUU7V:-KRhP5iUcMjdExYRUU7W:bmn0vy4) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L66)):_

> ``` Java
>     @Override
>     public Stream<Product> apply(Query t) {
>         // TODO: Align the query to pages in a sensible way.
> ```

when and where to address the TODO?

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudLogic.java, line 58 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhODom3h65h0q0C5YW:-KRhODom3h65h0q0C5YX:bgrd34d) ([raw file](https://github.com/vaadin/framework8-demo/blob/4fef8933fd55069d9c3bfa98261941c0b6bed60e/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudLogic.java#L58)):_

> ``` Java
>         }
> 
>         view.showProducts(dataService.getAllProducts());
> ```

no longer needed?

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 61 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhOZ141G-0aZRuirtR:-KRhOZ1559J1xFOtqAmk:b-z993ga) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L61)):_

> ``` Java
>         filter.setImmediate(true);
>         filter.addValueChangeListener(
>                 event -> dataSource.setFilterText(event.getValue()));
> ```

how is this supposed to be done later if the data source should be stateless?

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 121 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhOlY-3qYL9Lhnauxe:-KRhOlY-3qYL9Lhnauxf:b7md435) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L121)):_

> ``` Java
>     public void refreshProduct(Product product) {
>         dataSource.save(product);
>         // TODO: Grid used to scroll to the updated item
> ```

(does this TODO require changes in the demo, or just a ticket for the framework?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by tsuoanttila** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_[spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/ProductRepository.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRgxxH29DaSmnVTbnuV:-KRhZ__6wkEzf0GfVUMd:b-svdqc) ([raw file](https://github.com/vaadin/framework8-demo/blob/4c15f1a6f27da15dde14deb3dadd30837cf3ef8f/spring-demo/spring-demo-backend/src/main/java/com/vaadin/framework8/samples/backend/repository/ProductRepository.java#L36)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> why removed transactional?
> </details>
> Transactional restored.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 66 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhP5iUcMjdExYRUU7V:-KRhZd1piNqodoZKbAka:bgr17ur) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L66)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> when and where to address the TODO?
> </details>
> there was a discussion on this topic with Leif earlier today. Something needs to be done, I'd say a special case in this demo at this point and make it more generic later.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudLogic.java, line 58 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhODom3h65h0q0C5YW:-KRhZpj-8gnyHG4u6tTq:b-s3aq63) ([raw file](https://github.com/vaadin/framework8-demo/blob/4fef8933fd55069d9c3bfa98261941c0b6bed60e/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudLogic.java#L58)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> no longer needed?
> </details>
> No longer needed. the View sets the data source for product grid and data source manages things from there onward.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 61 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhOZ141G-0aZRuirtR:-KRh_-i9GMRx1kOC9zTp:b-rffk60) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L61)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> how is this supposed to be done later if the data source should be stateless?
> </details>
> I'd say we need some more or less generic API on the abstract listing level to add custom backend filters. Said method is still not implemented at all on the FW side, so we need to take a good look at that design.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 121 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhOlY-3qYL9Lhnauxe:-KRh_AE3q3ECpGQNZW2t:b-z3jpkq) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L121)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (does this TODO require changes in the demo, or just a ticket for the framework?)
> </details>
> Missing feature from the framework, re-enable in demo after that

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 66 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhP5iUcMjdExYRUU7V:-KRhlIkNV9UWlguYqdrK:b-mnyr1f) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L66)):_
<details><summary>

<i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary>



> there was a discussion on this topic with Leif earlier today. Something needs to be done, I'd say a special case in this demo at this point and make it more generic later.
> </details>
> remove TODO here and handle in Pageable?

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 113 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhlGGAG3c7lXAftizg:-KRhlGGAG3c7lXAftizh:be7zfzb) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L113)):_

> ``` Java
> 
>     private Pageable getPageable(Query q) {
>         // TODO: Calculate page more correctly to avoid requesting extra items.
> ```

TODO?
it is hard for me to understand this code (mostly from the point of view of the Pageable, which came already in an earlier changeset)

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 41 at r4](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhnw2Kepr91mXtRlVi:-KRhnw2LHh1BW5Uo8DI3:bt8pj9x) ([raw file](https://github.com/vaadin/framework8-demo/blob/b690580de22f65e834dd56fd3de9c37971bb6eb4/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L41)):_

> ``` Java
>  */
> @Component
> // TODO: Use common data source for all UIs after backend filtering is done
> ```

needs thought in framework - this can be used as a sample case for how to pass the filter to the correct place (query?)

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 94 at r4](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhnNkuxdICX_amirJ1:-KRhnNkvAq5VE3fV4XZz:b-q5ctan) ([raw file](https://github.com/vaadin/framework8-demo/blob/b690580de22f65e834dd56fd3de9c37971bb6eb4/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L94)):_

> ``` Java
>     private List<Availability> getFilteredAvailabilities(String string) {
>         Locale locale = UI.getCurrent().getLocale();
>         return Arrays.stream(Availability.values()).filter(a -> {
> ```

(block and return not really necessary)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by pleku** [comment]
Reviewed 3 of 6 files at r1, 3 of 5 files at r3, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 135 at r7](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KSk97YDRvb9d4PLvJbV:-KSk97YE0NeS2Zpv_-XP:b6l6stw) ([raw file](https://github.com/vaadin/framework8-demo/blob/04c4d10ee644c92a067fa205b389b07757f382a7/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L135)):_

> ``` Java
>             p.pageable = getPageRequest(q, 0, end);
>             p.pageOffset = q.getOffset();
>         } else {
> ```

what is the purpose of this `else`?
figure out some page size based on some logic?
please clarify in code (comments) and/or isolated method for why/what it does here

---

_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 119 at r7](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KSkAHQUNOX-hEmcl95d:-KSkAHQUNOX-hEmcl95e:b79o5hc) ([raw file](https://github.com/vaadin/framework8-demo/blob/04c4d10ee644c92a067fa205b389b07757f382a7/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L119)):_

> ``` Java
>     }
> 
>     public void refreshProduct(Product product) {
> ```

Kinda weirdly named method if it results in a saving something in the DB

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java, line 119 at r7](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KSkAHQUNOX-hEmcl95d:-KSpKAfyiZoZdWuApabp:b7jtedl) ([raw file](https://github.com/vaadin/framework8-demo/blob/04c4d10ee644c92a067fa205b389b07757f382a7/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/SampleCrudView.java#L119)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Kinda weirdly named method if it results in a saving something in the DB
> </details>
> I have just tried to avoid making API changes. Can update the name.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 41 at r4](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhnw2Kepr91mXtRlVi:-KSpKxTlNLJ3Hj1r8vFe:b-r7var3) ([raw file](https://github.com/vaadin/framework8-demo/blob/b690580de22f65e834dd56fd3de9c37971bb6eb4/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L41)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> needs thought in framework - this can be used as a sample case for how to pass the filter to the correct place (query?)
> </details>
> Needs thought in framework, I do have a plan on how to implement this once the framework support is actually implemented. Opened a new ticket for it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 113 at r3](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KRhlGGAG3c7lXAftizg:-KSpL6HixLKblJ0HObmT:bt2vr1b) ([raw file](https://github.com/vaadin/framework8-demo/blob/466fcbf70b95a3a0961a2ac9098337b1a6de51ac/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L113)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> TODO?
> it is hard for me to understand this code (mostly from the point of view of the Pageable, which came already in an earlier changeset)
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by tsuoanttila** [comment]
_[spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java, line 135 at r7](https://reviewable.io:443/reviews/vaadin/framework8-demo/27#-KSk97YDRvb9d4PLvJbV:-KSpMcXZ4WzlGoPOc7sJ:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/04c4d10ee644c92a067fa205b389b07757f382a7/spring-demo/spring-demo-ui/src/main/java/com/vaadin/framework8/samples/crud/ProductDataSourceImpl.java#L135)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> what is the purpose of this `else`?
> figure out some page size based on some logic?
> please clarify in code (comments) and/or isolated method for why/what it does here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/27)_

**Pull request merged**
