### PR TITLE
Remove unnecessary cross field validation

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/18)

### CODE REVIEW

**Comment by Legioth** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 77 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYYB-kkVys-pXcplO:-KQtYYB-kkVys-pXcplP:b-3bkaq1) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L77)):_

> ``` Java
>                         new NotEmptyValidator<>("Full name may not be empty"))
>                 .withStatusChangeHandler(this::commonStatusChangeHandler);
>         fullNameField
> ```

Why is this needed? Doesn't the binding automatically validate itself when its own field changes?

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 86 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYl07b3lFrVZ-c-pF:-KQtYl07b3lFrVZ-c-pG:b-3bkaq1) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L86)):_

> ``` Java
>                 .withValidator(new EmailOrPhoneValidator())
>                 .withStatusChangeHandler(this::commonStatusChangeHandler);
>         phoneOrEmailField.addValueChangeListener(
> ```

Why is this needed? Doesn't the binding automatically validate itself when its own field changes?

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 97 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYmmDTyoGwOahadrA:-KQtYmmDTyoGwOahadrB:b-3bkaq1) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L97)):_

> ``` Java
>                 .withStatusChangeHandler(this::commonStatusChangeHandler);
>         passwordField.addValueChangeListener(event -> {
>             passwordBinding.validate();
> ```

Why is this needed? Doesn't the binding automatically validate itself when its own field changes?

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 114 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYo3MepGdHYD5QrRa:-KQtYo3MepGdHYD5QrRb:b-3bkaq1) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L114)):_

> ``` Java
>         confirmPasswordField.addValueChangeListener(event -> {
>             passwordBinding.validate();
>             confirmPasswordBinding.validate();
> ```

Why is this needed? Doesn't the binding automatically validate itself when its own field changes?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 77 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYYB-kkVys-pXcplO:-KQtyY3AvxQcv6_-ZU-t:b-xlly8t) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L77)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> Why is this needed? Doesn't the binding automatically validate itself when its own field changes?
> </details>
> No binder status change is fired from the listener that .bind() adds to the field, so no visible error is shown in the current implementation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 77 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYYB-kkVys-pXcplO:-KQyyUiPy5GglRMVC5Wo:b-po0m5r) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L77)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> No binder status change is fired from the listener that .bind() adds to the field, so no visible error is shown in the current implementation.
> </details>
> Sounds like a bug in Binder and not something that we should just hack around in the demos?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by ahie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 77 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KQtYYB-kkVys-pXcplO:-KR7gunVB5_pmtc5EpIs:bsjgt3j) ([raw file](https://github.com/vaadin/framework8-demo/blob/975a9613d2c1f8f5f4579ff243b21e6368a02e74/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L77)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> Sounds like a bug in Binder and not something that we should just hack around in the demos?
> </details>
> removed calls to validate, build will pass once binder has been fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 103 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KRDDiOvanYMTBbdvwIJ:-KRDDiOvanYMTBbdvwIK:b-z3bacd) ([raw file](https://github.com/vaadin/framework8-demo/blob/05637ee000fb566cb2e7cff7fda984e3c93417f2/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L103)):_

> ``` Java
>                 .bind(Person::getPassword, (person, pwd) -> {
>                 });
>         confirmPasswordField
> ```

How does the confirmation field affect the validation status of the password field?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by ahie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 103 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KRDDiOvanYMTBbdvwIJ:-KRDL7RUq6Vhhbm-USJ_:ba3dfob) ([raw file](https://github.com/vaadin/framework8-demo/blob/05637ee000fb566cb2e7cff7fda984e3c93417f2/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L103)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> How does the confirmation field affect the validation status of the password field?
> </details>
> Removed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 103 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KRDDiOvanYMTBbdvwIJ:-KRDVrKO5lL5OtknN27t:b3oq0ca) ([raw file](https://github.com/vaadin/framework8-demo/blob/05637ee000fb566cb2e7cff7fda984e3c93417f2/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L103)):_
<details><summary>

<i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary>



> Removed
> </details>
> The `passwordBinding` instance field should not be needed any more now.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 103 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/18#-KRDDiOvanYMTBbdvwIJ:-KRDWdDt8fZCUMksDeAc:ba7r4ob) ([raw file](https://github.com/vaadin/framework8-demo/blob/05637ee000fb566cb2e7cff7fda984e3c93417f2/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L103)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> The `passwordBinding` instance field should not be needed any more now.
> </details>
> used in validateConfirmPasswd

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/18)_

**Pull request merged**
