### PR TITLE
Addressbook Vaadin 8 version (#9)

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/3)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 3 of 18 files at r1, 2 of 2 files at r2.
Review status: 5 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOOMEOpJlqJhnJAwXbf:-KOOMEOpJlqJhnJAwXbg:b-hpkbla) (no related file):_
Needs a TB test or two

---

_[addressbook/pom.xml, line 16 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOKhsgVYFPHISOkIy3k:-KOKhsgVYFPHISOkIy3l:bkyuy9t) ([raw file](https://github.com/vaadin/framework8-demo/blob/c28581a1a13046e7e517f980e9414093332eb9f2/addressbook/pom.xml#L16)):_

> ``` XML
> 
>   <properties>
>       <failOnMissingWebXml>false</failOnMissingWebXml>
> ```

This could be in the parent pom, valid for all demos

---

_[addressbook/pom.xml, line 23 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOKhvCIpd0F804R7hUD:-KOKhvCIpd0F804R7hUE:bkyuy9t) ([raw file](https://github.com/vaadin/framework8-demo/blob/c28581a1a13046e7e517f980e9414093332eb9f2/addressbook/pom.xml#L23)):_

> ``` XML
>       <repository>
>           <id>vaadin-addons</id>
>           <url>http://maven.vaadin.com/vaadin-addons</url>
> ```

This could be in the parent pom, valid for all demos

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Comment by denis-anisimov** [comment]
Review status: 5 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOOMEOpJlqJhnJAwXbf:-KOOMVxTv8j569OanmoA:b-7lh4w8) (no related file):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Needs a TB test or two
> </details>
> True, but it will require changes for common TB tests infrastructure to support any demo project (like in HB f.e.).
> Those changes are not really related to addressbook demo.....
> So I'm not so sure that they should be included in this PR.

---

_[addressbook/pom.xml, line 16 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOKhsgVYFPHISOkIy3k:-KOON98P-pT8Y9rPxfXb:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/c28581a1a13046e7e517f980e9414093332eb9f2/addressbook/pom.xml#L16)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> This could be in the parent pom, valid for all demos
> </details>
> Done.

---

_[addressbook/pom.xml, line 23 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOKhvCIpd0F804R7hUD:-KOON9S8rvb0_vyCfE0o:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/c28581a1a13046e7e517f980e9414093332eb9f2/addressbook/pom.xml#L23)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> This could be in the parent pom, valid for all demos
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Comment by Artur-** [comment]
Reviewed 13 of 18 files at r1, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ActionsBar.java, line 31 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPyIzZYFB3JpipF9z1:-KOPyIz_871f4-e34hJI:bywlb9i) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ActionsBar.java#L31)):_

> ``` Java
>  */
> @DesignRoot
> public class ActionsBar extends HorizontalLayout {
> ```

What is the reason for this being a separate class, there is no logic at all inside the class, just a custom way of exposing listeners for the textfield and the button?

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 28 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPtLZ6SELK6t4WQ6Mh:-KOPtLZ7KqVvYz0hNpgh:b-9jr0sh) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L28)):_

> ``` Java
> @Theme("valo")
> public class AddressbookUI extends UI
>         implements Function<String, List<Contact>>, Consumer<Contact> {
> ```

this should not implement generic Function and Consumer, why not call ContactService.getDemoService() directly when needed ?

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactFormActionsBar.java, line 18 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPwfDk9H11ZLiGmCxz:-KOPwfDk9H11ZLiGmCy-:b-7f13mb) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactFormActionsBar.java#L18)):_

> ``` Java
> 
> @DesignRoot
> public class ContactFormActionsBar extends HorizontalLayout {
> ```

Why is part of the form separated from the form?

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/MainLayout.java, line 75 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPxTvx27xhKRaQu2ox:-KOPxTvx27xhKRaQu2oy:b-26trp) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/MainLayout.java#L75)):_

> ``` Java
>             left.refresh(stringFilter);
>         }
>         contactForm.setVisible(false);
> ```

The grid should never change size, see http://demo.vaadin.com/addressbook/

---

_[addressbook/src/main/resources/com/vaadin/tutorial/addressbook/MainLayout.html, line 12 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPxhGxM4U86kzppCz-:-KOPxhGxM4U86kzppCz0:b-vcnttb) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/resources/com/vaadin/tutorial/addressbook/MainLayout.html#L12)):_

> ``` HTML
>   </vaadin-horizontal-layout>  
>  </body>
> </html>
> ```

Add new line at the end of all html files

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ActionsBar.java, line 31 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPyIzZYFB3JpipF9z1:-KOQZGDo-zEGMNt_gCzB:b-gdc6us) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ActionsBar.java#L31)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> What is the reason for this being a separate class, there is no logic at all inside the class, just a custom way of exposing listeners for the textfield and the button?
> </details>
> Good question.
> Done.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 28 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPtLZ6SELK6t4WQ6Mh:-KOQ__DaCOulHgrlVvFX:bb6un1j) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L28)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> this should not implement generic Function and Consumer, why not call ContactService.getDemoService() directly when needed ?
> </details>
> Done

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactFormActionsBar.java, line 18 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPwfDk9H11ZLiGmCxz:-KOQaD2Era6VAN_xC0dl:bu27glt) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactFormActionsBar.java#L18)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Why is part of the form separated from the form?
> </details>
> Same reason as top level actions bar: I'm an idiot.
> But here it has sense actually. It allows to have separate content for UI controls and logic which handles actions.
> I would suggest to keep it as is.
> Classes became smaller and more readable.

But this could be merged into ContactForm if you think it's better.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/MainLayout.java, line 75 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPxTvx27xhKRaQu2ox:-KOQbTSSBSqaxW_KNvA4:b5wclo3) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/MainLayout.java#L75)):_

> http://demo.vaadin.com/addressbook/
> Hm, it uses splitpanel. Original version has no split panel. 
> See source code : https://github.com/vaadin/addressbook/blob/master/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java
> HorizontalLayout is used instead of HSP.
> But OK.

---

_[addressbook/src/main/resources/com/vaadin/tutorial/addressbook/MainLayout.html, line 12 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPxhGxM4U86kzppCz-:-KOQcuqnNWORMnnan-KS:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/resources/com/vaadin/tutorial/addressbook/MainLayout.html#L12)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Add new line at the end of all html files
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Comment by svigani4ok** [comment]
Review status: 8 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 21 [r5]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOQvfYlq4cMU6oE5FKo:-KOQvfYmyQ8Jk5sVeJoT:b-i8tp4v) ([raw file](https://github.com/vaadin/framework8-demo/blob/ca9222e91ed35e82547658c5dab1b31f760e0eae/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L21)):_

> ``` Java
>  */
> @Title("Addressbook")
> @Theme("valo")
> ```

Use constant instead of a string.

``` java
com.vaadin.ui.themes.ValoTheme.THEME_NAME
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Comment by denis-anisimov** [comment]
Review status: 8 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java, line 21 [r5]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOQvfYlq4cMU6oE5FKo:-KOTWLVWwk67TgGsHD2p:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/ca9222e91ed35e82547658c5dab1b31f760e0eae/addressbook/src/main/java/com/vaadin/tutorial/addressbook/AddressbookUI.java#L21)):_
<details><summary>

<i>Previously, sviga (svigani4ok) wrote…</i></summary>



> Use constant instead of a string.
> 
> ``` java
> com.vaadin.ui.themes.ValoTheme.THEME_NAME
> ```
> 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Comment by Artur-** [comment]
Reviewed 8 of 10 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactFormActionsBar.java, line 18 [r4]](https://reviewable.io:443/reviews/vaadin/framework8-demo/3#-KOPwfDk9H11ZLiGmCxz:-KOiD4aIIEdz3ljdlEIh:buczfwu) ([raw file](https://github.com/vaadin/framework8-demo/blob/45f1a96fe25ef0b556ae30738fa441b6053f6289/addressbook/src/main/java/com/vaadin/tutorial/addressbook/ContactFormActionsBar.java#L18)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> Same reason as top level actions bar: I'm an idiot.
> But here it has sense actually. It allows to have separate content for UI controls and logic which handles actions.
> I would suggest to keep it as is.
> Classes became smaller and more readable.
> 
> But this could be merged into ContactForm if you think it's better.
> </details>
> Works for me, at least for now :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/3)_

**Pull request merged**
