### PR TITLE
Make code demoable; Check for empty password  confirmation

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/16)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 147 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PI_nRtMJXwWsxRvI:-KQ_PI_nRtMJXwWsxRvJ:b-z7825r) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L147)):_

> ``` Java
> 
>     private void save() {
>         boolean ok = binder.validate().isEmpty();
> ```

It would be even simpler to remove the `binder.validate()` part and just try to save using `saveIfValid`

This version looks like you HAVE TO do validate yourself

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Comment by Artur-** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java, line 40 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PqR2CKxQQXlRsErZ:-KQ_PqR2CKxQQXlRsEr_:b-g0ockj) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java#L40)):_

> ``` Java
>                 !hasLetter(value))
>             return Result
>                     .error(PASSWORD_RULE_MESSAGE);
> ```

This is no longer fulfilling the specs with two different messages

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Comment by elmot** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java, line 40 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PqR2CKxQQXlRsErZ:-KQ_UKOxhLJTJZ7YCC1l:b-5ek3f0) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java#L40)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> This is no longer fulfilling the specs with two different messages
> </details>
> I'd prefer another spec. That is really bad UX - display password limitations one-by-one, a regular user needs to find several passwords in a row. 

---

_[registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java, line 147 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PI_nRtMJXwWsxRvI:-KQ_ZZ-7VE7LJ8cCWQ79:bb6un1j) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/RegistrationFormUI.java#L147)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> It would be even simpler to remove the `binder.validate()` part and just try to save using `saveIfValid`
> 
> This version looks like you HAVE TO do validate yourself
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java, line 40 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PqR2CKxQQXlRsErZ:-KQ_cFl6_MLMlCrFTEeV:brudoo0) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java#L40)):_
<details><summary>

<i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>



> I'd prefer another spec. That is really bad UX - display password limitations one-by-one, a regular user needs to find several passwords in a row. 
> </details>
> ok, but this commit says "make code demoable", not "redefine the demo"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Comment by elmot** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java, line 40 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PqR2CKxQQXlRsErZ:-KQ_r9WDh6QnXO2p3287:b-uncjq8) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java#L40)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> ok, but this commit says "make code demoable", not "redefine the demo"
> </details>
> I hate that but it's reverted.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java, line 40 [r1]](https://reviewable.io:443/reviews/vaadin/framework8-demo/16#-KQ_PqR2CKxQQXlRsErZ:-KQ_rig0HIFXBnbqRMcd:b-s3w4ep) ([raw file](https://github.com/vaadin/framework8-demo/blob/31e2c841ed64394a818ca6afe527e8497e5adc3e/registration-form/src/main/java/com/vaadin/demo/registration/PasswordValidator.java#L40)):_
<details><summary>

<i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>



> I hate that but it's reverted.
> </details>
> The specs are more or less 100% https://twitter.com/signup

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/16)_

**Pull request merged**
