### PR TITLE
Enable Travis build for pull requests and master

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/2)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[.travis.script.sh, line 12 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/2#-KOJfyMiEIP44POucDB_:-KOJfyMiEIP44POucDBa:-886302893) ([raw file](https://github.com/vaadin/framework8-demo/blob/d45e6d23bbc91fcc03e07f8db7c9c07ed8cb4199/.travis.script.sh#L12)):_

> TESTBENCH_LICENSE
> Where it is specified ?
> And since there are some comments for other variables it should be included there as well ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/2)_

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[.travis.script.sh, line 12 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/2#-KOJfyMiEIP44POucDB_:-KOJgE3nOkQpgPu0l814:1554059536) ([raw file](https://github.com/vaadin/framework8-demo/blob/d45e6d23bbc91fcc03e07f8db7c9c07ed8cb4199/.travis.script.sh#L12)):_
<details><summary>

<i>Previously, denis-anisimov wrote…</i></summary>



> > TESTBENCH_LICENSE
> > Where it is specified ?
> > And since there are some comments for other variables it should be included there as well ?
> > </details>
> > in the Travis UI, let me move it to .travis.yml for clarity

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/2)_

**Comment by Artur-** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[.travis.script.sh, line 12 [r2]](https://reviewable.io:443/reviews/vaadin/framework8-demo/2#-KOJfyMiEIP44POucDB_:-KOJj-gZVDbmB_eFxI1b:603492162) ([raw file](https://github.com/vaadin/framework8-demo/blob/d45e6d23bbc91fcc03e07f8db7c9c07ed8cb4199/.travis.script.sh#L12)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> in the Travis UI, let me move it to .travis.yml for clarity
> </details>
> Well, not that clear as it is encrypted... anyway, it is there :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/2)_

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/2)_

**Pull request merged**
