### PR TITLE
Correct demos because of recent API changes.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#433

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/43)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/framework8-demo/43#-KVZ1OV1WuaRsSLkT90b:-KVZ1OV2Kb3hGk0LFrbP:bjehx6q) (no related file):_
Still missing some changes, also this is sort of a duplicate of #42 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/43)_

**Comment by denis-anisimov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/framework8-demo/43#-KVZ1OV1WuaRsSLkT90b:-KVZ22VLpgXiXnsTDROk:b4aiqk3) (no related file):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> Still missing some changes, also this is sort of a duplicate of #42 
> </details>
> Kind of duplicate: I've fixed all errors to be able to build.
> But main changes are about ValidationResult 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/43)_

**Comment by pleku** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/43)_

**Comment by denis-anisimov** [comment]
All tests pass with fix for static resources handling.

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/43#-:-KWlVQSuEwe9ig7H6Ojq:bnfp4nl)_

**Pull request closed without merging**
