### PR TITLE
Use updated DateField. Display birthdate instead of created

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/33)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/33#-KT8kkxwQzJzsIHh0zb9:-KT8kkxwQzJzsIHh0zbA:bq2gfb) ([raw file](https://github.com/vaadin/framework8-demo/blob/c6e8986e04468ecb8e3661a6883b8e7b1e4a466e/addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java#L74)):_

> ``` Java
>         contactList.addColumn("Birth Date",
>                 c -> Date.from(c.getBirthDate().atStartOfDay()
>                         .atZone(ZoneId.systemDefault()).toInstant()),
> ```

This is incorrect in reality since it depends on default system zone. But it shouldn't.

Do we really need `Date` here as a type for column ?
Can it be just a String ?
In that case you can just provide a "toString()" method which uses DateTimeFormatter to translate LocalDate to String immediately  without interim wrong Date conversation.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33)_

**Comment by pleku** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/33#-KT8kkxwQzJzsIHh0zb9:-KT8o8zqANbQCqqRD42S:bobzeny) ([raw file](https://github.com/vaadin/framework8-demo/blob/c6e8986e04468ecb8e3661a6883b8e7b1e4a466e/addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java#L74)):_
<details><summary>

<i>Previously, denis-anisimov (Denis) wrote…</i></summary>



> This is incorrect in reality since it depends on default system zone. But it shouldn't.
> 
> Do we really need `Date` here as a type for column ?
> Can it be just a String ?
> In that case you can just provide a "toString()" method which uses DateTimeFormatter to translate LocalDate to String immediately  without interim wrong Date conversation.
> </details>
> I tried to figure out why DateRenderer would be needed.
> I think it is because of sorting, if the type is String, then it would not be sorted right.
> Another thing would be the Editor row, but is NOT enabled so that doesn't need the real type.

I anyways created an issue about changing the type of DateRenderer to something else than Date, like Instant.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33)_

**Comment by denis-anisimov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/33#-KT8kkxwQzJzsIHh0zb9:-KT8pQnPRFFP8azwP0Dj:b-kclch5) ([raw file](https://github.com/vaadin/framework8-demo/blob/c6e8986e04468ecb8e3661a6883b8e7b1e4a466e/addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java#L74)):_
<details><summary>

<i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>



> I tried to figure out why DateRenderer would be needed.
> I think it is because of sorting, if the type is String, then it would not be sorted right.
> Another thing would be the Editor row, but is NOT enabled so that doesn't need the real type.
> 
> I anyways created an issue about changing the type of DateRenderer to something else than Date, like Instant.
> </details>
> OK, makes sense......
> But would it be better to provide a custom renderer here for a `LocalDate` instead of bad `Date` conversation ?
> Is it a lot of work ? Should be quite easy I guess.

Then it can be replaced to the core one (please create an issue to replace it here)...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33)_

**Comment by pleku** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/33#-KT8kkxwQzJzsIHh0zb9:-KT8zvOG-U94A51hjk42:b-lgs2m) ([raw file](https://github.com/vaadin/framework8-demo/blob/c6e8986e04468ecb8e3661a6883b8e7b1e4a466e/addressbook/src/main/java/com/vaadin/tutorial/addressbook/LeftPanel.java#L74)):_
<details><summary>

<i>Previously, denis-anisimov (Denis) wrote…</i></summary>



> OK, makes sense......
> But would it be better to provide a custom renderer here for a `LocalDate` instead of bad `Date` conversation ?
> Is it a lot of work ? Should be quite easy I guess.
> 
> Then it can be replaced to the core one (please create an issue to replace it here)...
> </details>
> Can't extend DateRenderer and extending AbstractRenderer<Object, Date> would require a new client side renderer class it seems (why oh why).

Sure, I'll create another ticket about updating this demo after creating those  new renderers

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33)_

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33)_

**Comment by elmot** [comment]
It seems to me, Person.birthdate should be LocalDate. If a human moves from Japan to USA, he/she does not change his formal date of celebration, he/she just celebrates using another time zone.

**Comment by pleku** [comment]
It, still, is LocalDate...

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33#-:-KT9gt1F0Bu8DR_WfOzE:b-aft6zx)_

**Comment by elmot** [comment]
In this PR it is already not
https://github.com/vaadin/framework8-demo/pull/32

(I did not want change anything but just wanted the project to be compilable)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33#-:-KT9jzQ1AiM2yYp9aflg:b9ikglw)_

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/33)_

**Pull request merged**
