### PR TITLE
Backend JDBC filtering; Connection pool support

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-demo/53)

### CODE REVIEW

**Comment by elmot** [comment]
Fixes vaadin/framework8-issues#489

**Comment by hesara** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZj8eWCm3fvTJW0-7F:-KXZj8eWCm3fvTJW0-7G:bt7t7dg) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java#L59)):*
> ```Java
> 
>     @Override
>     public int size(Query<F> query) {
> ```

this will require some further changes if https://dev.vaadin.com/review/#/c/14822/ is merged

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/PreparedJDBCDataProvider.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZih1Gk0wFdzakCVTE:-KXZih1HK5SPI7ZcFaKy:b2nhz1u) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/PreparedJDBCDataProvider.java#L27)):*
> ```Java
> 
> /**
>  * Vaadin DataProvider over pure JDBC. Filtering ans sorting to be implemented
> ```

and

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/SimpleJDBCDataProvider.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZk4scN7ojwctygvZl:-KXZk4scN7ojwctygvZm:brstc3d) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/SimpleJDBCDataProvider.java#L30)):*
> ```Java
>  * @author Vaadin Ltd
>  */
> public class SimpleJDBCDataProvider<T> extends PreparedJDBCDataProvider<T,Void> {
> ```

is this class used anywhere anymore?

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZmBz7EIFLe0WU3ns4:-KXZmBz7EIFLe0WU3ns5:bxqbui7) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L29)):*
> ```Java
>  * JDBC DataProvider implementation with filtering supported.
>  */
> class TodoJDBCDataProvider extends PreparedJDBCDataProvider<Todo, Supplier<TaskFilter>> {
> ```

I'm a bit torn whether using a supplier as the hard-coded parameter here is a good practice or not - probably fine, though, as this data provider is really an application level class.

Is this class package protected on purpose?

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZlqusDlAWQwi68zRz:-KXZlqut4dbZUOIOfyPp:bsz4mmf) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L33)):*
> ```Java
>     public TodoJDBCDataProvider(
>             Connection connection) throws SQLException {
>         super(connection, "SELECT * FROM todo WHERE completed = ? or ?", resultSet ->
> ```

This looks like a hack to me to enable using just one query. Should this be at least mentioned in some comment?

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoModel.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZlPd_wmfSyVBzitdK:-KXZlPd_wmfSyVBzitdL:b-cwj1z8) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoModel.java#L44)):*
> ```Java
>     private static final BasicDataSource dataSource;
> 
>     static {
> ```

(I don't really like doing such things as a static block as troubleshooting becomes very hard if anything goes wrong in a static block, and the block is executed very early when something might not be properly set up yet.)

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoView.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZkTWaKHER13ZZD61t:-KXZkTWaKHER13ZZD61u:bkzn49g) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoView.java#L13)):*
> ```Java
>     void updateCounters(int completed, int active);
> 
>     void setDataProvider(TodoJDBCDataProvider dataProvider);
> ```

why is this method still needed in the view interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/SimpleJDBCDataProvider.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZk4scN7ojwctygvZl:-KXf2PgIAkrT5ct4cb0r:bvp2wpc) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/SimpleJDBCDataProvider.java#L30)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is this class used anywhere anymore?
</blockquote></details>

This class is used in tests, and it could be used for simplest cases (unfiltered queries) in real applications. I'd prefer to keep it here and expose as a part of JDBC support API.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZmBz7EIFLe0WU3ns4:-KXf7VwAu6F6DKB38CBS:b-a6rl3m) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm a bit torn whether using a supplier as the hard-coded parameter here is a good practice or not - probably fine, though, as this data provider is really an application level class.

Is this class package protected on purpose?
</blockquote></details>

Yes, this is kinda business-logic class, that is fine imho here. Might be Task**Filter** is a bit misleading here. I'll probably change naming in the next patch.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZlqusDlAWQwi68zRz:-KXf8Dg7Vc5ojoHd3YlO:b-ntm8xu) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This looks like a hack to me to enable using just one query. Should this be at least mentioned in some comment?
</blockquote></details>

Well, sounds reasonable. Might be it's better to make superclass of this a bit more flexible and have an ability to have as many different statements as it's needed.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoModel.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZlPd_wmfSyVBzitdK:-KXf8cJedIfJ1nppyxQW:b38ulxc) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoModel.java#L44)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I don't really like doing such things as a static block as troubleshooting becomes very hard if anything goes wrong in a static block, and the block is executed very early when something might not be properly set up yet.)
</blockquote></details>

Will be moved that to on-demand initializer.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoView.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZkTWaKHER13ZZD61t:-KXf8nL-u7At81dE5Abb:b-3tk2s3) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoView.java#L13)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

why is this method still needed in the view interface?
</blockquote></details>

I will try to decouple that again, but I am not sure if that gives any simplification. At least this method is now called only once during all the application life cycle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by elmot** [comment]
Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZj8eWCm3fvTJW0-7F:-KXfUqlFfUWAPI080yX2:blytr8q) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java#L59)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this will require some further changes if https://dev.vaadin.com/review/#/c/14822/ is merged
</blockquote></details>

sure. when that patch is ready.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/PreparedJDBCDataProvider.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZih1Gk0wFdzakCVTE:-KXfUpNjikKKwQUqcQGg:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/PreparedJDBCDataProvider.java#L27)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

and
</blockquote></details>

Done.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoModel.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZlPd_wmfSyVBzitdK:-KXfVF3PDnHu2tmFE4SN:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoModel.java#L44)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Will be moved that to on-demand initializer.
</blockquote></details>

Done.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoView.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZkTWaKHER13ZZD61t:-KXfUzvRBD2oTDSqox2k:b-fhtx1c) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoView.java#L13)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I will try to decouple that again, but I am not sure if that gives any simplification. At least this method is now called only once during all the application life cycle.
</blockquote></details>

I tried, and found that decoupling useless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by hesara** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZj8eWCm3fvTJW0-7F:-KXjo4ZxsBfaolrqEj6t:b-tb552s) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java#L59)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

sure. when that patch is ready.
</blockquote></details>

that patch and many others are now in

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXjrL3vqM0e6Vxzgp0l:-KXjrL3vqM0e6Vxzgp0m:b-ko22du) ([raw file](https://github.com/vaadin/framework8-demo/blob/f93a728a9580ce7072939c5ee21c8dac3ee2242f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L48)):*
> ```Java
>         });
> 
>         resultSetStatementFiltered =
> ```

this class now looks a bit long and complicated, but I still prefer this logic over the old one that was setting two magical booleans; I still wonder whether a switch/case or the current if is clearer in the *Statement() methods

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 84 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXjrCQJtv7IZaLh5N9a:-KXjrCQJtv7IZaLh5N9b:bwkq66z) ([raw file](https://github.com/vaadin/framework8-demo/blob/f93a728a9580ce7072939c5ee21c8dac3ee2242f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L84)):*
> ```Java
>     }
> 
>     private TaskFilter filterValue(Query<Supplier<TaskFilter>> query) {
> ```

should this be called getFilterValue()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by elmot** [comment]
Review status: 6 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXZj8eWCm3fvTJW0-7F:-KXk2ZzrDX9f1THcLs4m:b-896fix) ([raw file](https://github.com/vaadin/framework8-demo/blob/911268801edf0dd1804742d91e6491b47fc2cf06/todomvc/src/main/java/com/vaadin/tutorial/todomvc/AbstractJDBCDataProvider.java#L59)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

that patch and many others are now in
</blockquote></details>

Done.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXjrL3vqM0e6Vxzgp0l:-KXk2cX71ldzdfNkmerv:b-tkx29a) ([raw file](https://github.com/vaadin/framework8-demo/blob/f93a728a9580ce7072939c5ee21c8dac3ee2242f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L48)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this class now looks a bit long and complicated, but I still prefer this logic over the old one that was setting two magical booleans; I still wonder whether a switch/case or the current if is clearer in the *Statement() methods
</blockquote></details>

For demo/example purposes, I want to have here both approaches - parametric SQL and alternative SQL  statements. That is up to a developer to choose best one for a particular case.

---

*[todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java, line 84 at r2](https://reviewable.io:443/reviews/vaadin/framework8-demo/53#-KXjrCQJtv7IZaLh5N9a:-KXk36nwWb4crcIsyzwh:b-q1hyde) ([raw file](https://github.com/vaadin/framework8-demo/blob/f93a728a9580ce7072939c5ee21c8dac3ee2242f/todomvc/src/main/java/com/vaadin/tutorial/todomvc/TodoJDBCDataProvider.java#L84)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this be called getFilterValue()?
</blockquote></details>

IMHO, method should not be named as getter if it is not a getter. 'filterValue' is also not good, indeed. Let's use obtainFilterValue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework8-demo/53)*

**Pull request merged**
